- name: jira | systemctl daemon-reload
  systemd:
    daemon_reload: true
  changed_when: false
  ignore_errors: true

- name: jira | systemctl restart
  service:
    name: "jira"
    state: "restarted"
    enabled: true
